### ISSUE TITLE
Add nestjs v8 support

### ISSUE THREAD

**Issue by AlexanderBich** [SoftwareBrothers/adminjs-nestjs#28]
AdminBro seems to throw `[ExceptionHandler] Nest can't resolve dependencies of the AdminModule (?, AbstractLoader, CONFIG_TOKEN). Please make sure that the argument HttpAdapterHost at index [0] is available in the AdminModule context.` when upgrading to Nest.js v8.

P.S. The same setup with nestjs v7 works good

package.json
```
"dependencies": {
    "@admin-bro/express": "^3.1.0",
    "@admin-bro/nestjs": "^1.1.0",
    "@admin-bro/typeorm": "^1.4.0",
    "@nestjs/common": "^8.0.5",
    "@nestjs/config": "^1.0.1",
    "@nestjs/core": "^8.0.5",
    "@nestjs/platform-express": "^8.0.5",
    "@nestjs/typeorm": "8.0.2",
    "admin-bro": "^4.0.1",
    "express": "^4.17.1",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.2",
    "mongodb": "^4.0.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "typeorm": "^0.2.36"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.6.0",
    "@nestjs/schematics": "^8.0.2",
    "@nestjs/testing": "8.0.5",
    "@types/express": "^4.17.13",
    "@types/jest": "^26.0.24",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "jest": "^27.0.6",
    "prettier": "^2.3.2",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
```
admin.module.ts
```

@Module({
  imports: [
    AdminBroModule.createAdminAsync({
      imports: [],
      inject: [ConfigService],
      useFactory: (config: ConfigService) => ({
        adminBroOptions: {
          rootPath: '/admin',
          resources: [],
        },
        auth: {
          authenticate: async (email, password) => {
            if (
              config.get('admin.adminPassword') === password &&
              config.get('admin.adminEmail') === email
            ) {
              return {
                password: config.get('admin.adminPassword'),
                email: config.get('admin.adminEmail'),
              };
            }
            return null;
          },
          cookieName: 'cookie',
          cookiePassword: config.get('admin.cookiePassword'),
        },
      }),
    }),
  ],
})
export class AdminModule {}
```

Error message:
```
 ERROR [ExceptionHandler] Nest can't resolve dependencies of the AdminModule (?, AbstractLoader, CONFIG_TOKEN). Please make sure that the argument HttpAdapterHost at index [0] is available in the AdminModule context.

 Potential solutions:
 - If HttpAdapterHost is a provider, is it part of the current AdminModule?
 - If HttpAdapterHost is exported from a separate @Module, is that module imported within AdminModule?
   @Module({
     imports: [ /* the Module containing HttpAdapterHost */ ]
   })

 Error: Nest can't resolve dependencies of the AdminModule (?, AbstractLoader, CONFIG_TOKEN). Please make sure that the argument HttpAdapterHost at index [0] is available in the AdminModule context.

 Potential solutions:
 - If HttpAdapterHost is a provider, is it part of the current AdminModule?
 - If HttpAdapterHost is exported from a separate @Module, is that module imported within AdminModule?
   @Module({
     imports: [ /* the Module containing HttpAdapterHost */ ]
   })

     at Injector.lookupComponentInParentModules (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:193:19)
     at async Injector.resolveComponentInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:149:33)
     at async resolveParam (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:103:38)
     at async Promise.all (index 0)
     at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:118:27)
     at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:47:9)
     at async Injector.loadProvider (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:69:9)
     at async Promise.all (index 0)
     at async InstanceLoader.createInstancesOfProviders (/usr/src/app/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
     at async /usr/src/app/node_modules/@nestjs/core/injector/instance-loader.js:29:13
 error Command failed with exit code 1.
```

**Comment by AlexanderBich** [comment]
I guess it's related to this PR https://github.com/SoftwareBrothers/adminjs-nestjs/pull/25

**Comment by hichemfantar** [comment]
You're using an old version of the nestjs adapter that isn't compatible with v8.
Use the latest version of this one instead: https://www.npmjs.com/package/@adminjs/nestjs

**Comment by apperside** [comment]
the problem still persists with v3.0.0, this is my dependencies, I explained all details here @ https://github.com/SoftwareBrothers/adminjs-nestjs/issues/26#issuecomment-927882819

**Comment by hichemfantar** [comment]
@AlexanderBich Can you confirm that the problem still persists after properly installing the new packages?

**Comment by u2ru** [comment]
Having the same issue

```package.json
"dependencies": {
    "@admin-bro/nestjs": "^1.1.0",
    "@admin-bro/typeorm": "^1.4.0",
    "@nestjs/common": "^8.2.0",
    "@nestjs/core": "^8.2.0",
    "@nestjs/platform-express": "^8.2.0",
    "@nestjs/typeorm": "^8.0.2",
    "admin-bro": "^4.0.1",
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.1",
    "nuxt": "^2.15.8",
    "pg": "^8.7.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.0",
    "rxjs": "^7.4.0",
    "typeorm": "^0.2.40"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.1.4",
    "@nestjs/schematics": "^8.0.4",
    "@types/express": "^4.17.13",
    "@types/node": "^16.11.7",
    "copyfiles": "^2.4.1",
    "cross-env": "^7.0.3",
    "nodemon": "^2.0.15",
    "npm-run-all": "^4.1.5",
    "ts-loader": "^9.2.6",
    "ts-node": "^10.4.0",
    "tsconfig-paths": "^3.11.0",
    "typescript": "^4.4.4"
  }
```

```app.module.ts
import { Module } from '@nestjs/common';
import { NuxtController } from './nuxt.controller';
import { CompaniesModule } from './companies/companies.module';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CompaniesController } from './companies/companies.controller';
import { CompaniesService } from './companies/companies.service';
import { CompanyRepository } from './companies/company.repository';
import { AdminModule } from '@admin-bro/nestjs';
import adminBro from 'admin-bro';
import { Database, Resource } from '@admin-bro/typeorm';
import { CompanyEntity } from './companies/company.entity';

adminBro.registerAdapter({ Database, Resource })

@Module({
  imports: [
    CompaniesModule,
    TypeOrmModule.forRoot({
      type: 'postgres',
      host: 'localhost',
      port: 5432,
      username: 'postgres',
      password: 'postgres',
      database: 'task-management',
      autoLoadEntities: true,
      synchronize: true
    }),
    AdminModule.createAdmin({
      adminBroOptions: {
        rootPath: '/admin',
        resources: [CompanyEntity]
      },
      auth: {
        authenticate: async (email, password) => Promise.resolve({ email: 'test' }),
        cookieName: 'test',
        cookiePassword: 'testPass',
      },
    })
  ],
  controllers: [
    CompaniesController,
    NuxtController, //Put this at the last, so that Nest will check for all other controller first before going to Nuxt
  ],
  providers: [
    CompaniesService,
    CompanyRepository
  ]
})
export class AppModule {}

```

```cmd
[Nest] 73574  - 11/20/2021, 3:00:37 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the AdminModule (?, AbstractLoader, CONFIG_TOKEN). Please make sure that the argument HttpAdapterHost at index [0] is available in the AdminModule context.

Potential solutions:
- If HttpAdapterHost is a provider, is it part of the current AdminModule?
- If HttpAdapterHost is exported from a separate @Module, is that module imported within AdminModule?
  @Module({
    imports: [ /* the Module containing HttpAdapterHost */ ]
  })

Error: Nest can't resolve dependencies of the AdminModule (?, AbstractLoader, CONFIG_TOKEN). Please make sure that the argument HttpAdapterHost at index [0] is available in the AdminModule context.

Potential solutions:
- If HttpAdapterHost is a provider, is it part of the current AdminModule?
- If HttpAdapterHost is exported from a separate @Module, is that module imported within AdminModule?
  @Module({
    imports: [ /* the Module containing HttpAdapterHost */ ]
  })

    at Injector.lookupComponentInParentModules (/Users/lukaurushadze/Desktop/Code/persub/node_modules/@nestjs/core/injector/injector.js:202:19)
    at async Injector.resolveComponentInstance (/Users/lukaurushadze/Desktop/Code/persub/node_modules/@nestjs/core/injector/injector.js:157:33)
    at async resolveParam (/Users/lukaurushadze/Desktop/Code/persub/node_modules/@nestjs/core/injector/injector.js:108:38)
    at async Promise.all (index 0)
    at async Injector.resolveConstructorParams (/Users/lukaurushadze/Desktop/Code/persub/node_modules/@nestjs/core/injector/injector.js:123:27)
    at async Injector.loadInstance (/Users/lukaurushadze/Desktop/Code/persub/node_modules/@nestjs/core/injector/injector.js:52:9)
    at async Injector.loadProvider (/Users/lukaurushadze/Desktop/Code/persub/node_modules/@nestjs/core/injector/injector.js:74:9)
    at async Promise.all (index 0)
    at async InstanceLoader.createInstancesOfProviders (/Users/lukaurushadze/Desktop/Code/persub/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
    at async /Users/lukaurushadze/Desktop/Code/persub/node_modules/@nestjs/core/injector/instance-loader.js:29:13
    at async Promise.all (index 6)
    at async InstanceLoader.createInstances (/Users/lukaurushadze/Desktop/Code/persub/node_modules/@nestjs/core/injector/instance-loader.js:28:9)
    at async InstanceLoader.createInstancesOfDependencies (/Users/lukaurushadze/Desktop/Code/persub/node_modules/@nestjs/core/injector/instance-loader.js:18:9)
    at async /Users/lukaurushadze/Desktop/Code/persub/node_modules/@nestjs/core/nest-factory.js:93:17
    at async Function.asyncRun (/Users/lukaurushadze/Desktop/Code/persub/node_modules/@nestjs/core/errors/exceptions-zone.js:22:13)
    at async NestFactoryStatic.initialize (/Users/lukaurushadze/Desktop/Code/persub/node_modules/@nestjs/core/nest-factory.js:91:13)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by hichemfantar** [comment]
@u2ru read at my first comment and try that.

**Comment by MoureDeervarse** [comment]
hey guys, if you are still got errors related to HttpAdapterHost in nestjs v8.0.0, try upgrade version to 8.0.5.
And if you to get errors related to 'NoResourceAdapterError: There are no adapters supporting one of the resource you provided', write so that each entity inherits BaseEntity. (e.g. class User extends BaseEntity {})
when i did this in adminjs version 3.0.1 it worked.
