### ISSUE TITLE
@admin/nestjs not able to intialize prisma  

### ISSUE THREAD

**Issue by Xavier577** [SoftwareBrothers/adminjs-nestjs#46]
I am trying to integrate @adminjs/nestjs with my existing nestjs app which uses prisma.  I get an error that the modelMap property is not found on dmmf variable.

```
// error message
[app] Error     9/9/2022, 11:12:02 PM [ExceptionHandler] Cannot read properties of undefined (reading 'modelMap') - {"stack":["TypeError: Cannot read properties of undefined (reading 'modelMap')\n    at InstanceWrapper.useFactory [as metatype] (/src/app.module.ts:49:41)\n    at Injector.instantiateClass (/node_modules/@nestjs/core/injector/injector.js:333:55)\n    at callback (node_modules/@nestjs/core/injector/injector.js:48:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Injector.resolveConstructorParams (/node_modules/@nestjs/core/injector/injector.js:122:24)\n    at Injector.loadInstance (/node_modules/@nestjs/core/injector/injector.js:52:9)\n    at Injector.loadProvider (/node_modules/@nestjs/core/injector/injector.js:74:9)\n    at async Promise.all (index 3)\n    at InstanceLoader.createInstancesOfProviders (/node_modules/@nestjs/core/injector/instance-loader.js:44:9)\n    at /node_modules/@nestjs/core/injector/instance-loader.js:29:13"]} +1ms
```

```typescript
// app.module.ts
import {
  MiddlewareConsumer,
  Module,
  RequestMethod,
  ValidationPipe,
} from '@nestjs/common';
import AdminJS from 'adminjs';
import { AdminModule } from '@adminjs/nestjs';
import { APP_INTERCEPTOR, APP_PIPE } from '@nestjs/core';
import { AppController } from './app.controller';
import { Database, Resource } from '@adminjs/prisma';
import { DMMFClass } from '@prisma/client/runtime';
import { DatabaseModule } from '@database/database.module';
import { AuthenticationModule } from '@api/authentication/authentication.module';
import { BusinessModule } from '@api/business/business.module';
import { DocumentVerificationModule } from '@api/document-verification/document-verification.module';
import { AddressVerificationModule } from '@api/address-verification/address-verification.module';
import { PaymentModule } from '@api/payment/payment.module';
import { StoreFrontModule } from '@api/store-front/store-front.module';
import { WebhookModule } from '@api/webhook/webhook.module';
import { SecurityModule } from '@shared/modules/security/security.module';
import { UserModule } from '@api/user/user.module';
import { HttpModule } from '@nestjs/axios';
import { ErrorInterceptor } from '@common/interceptors/error.interceptor';
import { AuthMiddleware } from '@common/middlewares/auth.middleware';
import { CommunicationModule } from './api/communication/communication.module';
import { ReferralCodeModule } from './api/referral-code/referral-code.module';
import { OtpModule } from './api/otp/otp.module';
import { PrismaService } from '@database/prisma.service';

AdminJS.registerAdapter({ Resource, Database });
@Module({
  imports: [
    DatabaseModule,
    AdminModule.createAdminAsync({
      imports: [DatabaseModule],
      inject: [PrismaService],
      useFactory: async (prisma: PrismaService) => {
        const dmmf = (prisma as any)._dmmf as DMMFClass;
        return {
          adminJsOptions: {
            rootPath: '/admin',
            resources: [
              {
                resource: { model: dmmf.modelMap['User'], client: prisma },
                options: {},
              },
            ],
          },
        };
      },
    }),
    HttpModule,
    AuthenticationModule,
    BusinessModule,
    DocumentVerificationModule,
    AddressVerificationModule,
    PaymentModule,
    StoreFrontModule,
    WebhookModule,
    SecurityModule,
    UserModule,
    CommunicationModule,
    ReferralCodeModule,
    OtpModule,
  ],
  controllers: [AppController],
  providers: [
    { provide: APP_INTERCEPTOR, useClass: ErrorInterceptor },
    {
      provide: APP_PIPE,
      useValue: new ValidationPipe({
        whitelist: true,
        transform: true,
        errorHttpStatusCode: 400,
        stopAtFirstError: true,
      }),
    },
  ],
})
```

**Comment by dziraf** [comment]
Have you updated to the latest version of Prisma? They renamed `_dmmf` to `_baseDmmf`

**Comment by Xavier577** [comment]
Yes I am using the base version of Prisma, I was totally unaware of this. I have made the corrections and now my code works. Thank you very much.
